# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    # 4. Budowanie aplikacji
    - name: Build the application
      run: dotnet publish -c Release -o ./publish

    # 5. Instalowanie klucza ssh
    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} > ~/.ssh/konwn_hosts
    # 6. Przeniesienie zbudowanej aplikacji na serwer
    - name: Deploy to production server
      run: |
        rsync -vrm ./publish/* ${{ secrets.USER_IP }}:/home/dev/web/tiwms.tidev.pl/public_html
        ssh ${{ secrets.USER_IP }} "sudo systemctl restart tiwms"
